/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nzsoft.server;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

@SpringBootApplication
@Configuration
@ComponentScan(basePackages = "com.nzsoft.server")
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
