/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nzsoft.server;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Application classUnderTest = new Application();
        assertNotNull(classUnderTest, "finish the test here");
    }
}
